name: Conventional Commits

on:
  pull_request:
    branches:
      - main

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Conventional Commits
        uses: webiny/action-conventional-commits@v1.3.0
