name: Run Jest Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-jest-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Run Jest tests
        run: pnpm test
